### ISSUE TITLE
 undefined method `supports' for Chef::Resource::User::LinuxUser

### ISSUE THREAD

**Issue by zsan** [RiotGamesCookbooks/rbenv-cookbook#144]
I think its because of the cookbook is using `supports :manage_home => node[:rbenv][:manage_home]` ?

https://github.com/chef/chef/issues/5318

```
> chef --version
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```
and the error message:

```
NoMethodError
       -------------
       undefined method `supports' for Chef::Resource::User::LinuxUser
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/rbenv/recipes/default.rb:84:in `block in from_file'
         /tmp/kitchen/cache/cookbooks/rbenv/recipes/default.rb:81:in `from_file'
         /tmp/kitchen/cache/cookbooks/intake_rails/recipes/default.rb:13:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/rbenv/recipes/default.rb:
       
        77:  group node[:rbenv][:group] do
        78:    members node[:rbenv][:group_users] if node[:rbenv][:group_users]
        79:  end
        80:  
        81:  user node[:rbenv][:user] do
        82:    shell "/bin/bash"
        83:    group node[:rbenv][:group]
        84>>   supports :manage_home => node[:rbenv][:manage_home]
        85:    home node[:rbenv][:user_home]
        86:  end
````

**Comment by harryherbig** [comment]
👍
