### ISSUE TITLE
Upgrade ruby version

### ISSUE THREAD

**Issue by mbbernstein** [RiotGamesCookbooks/rbenv-cookbook#22]
Hi,

I'm having a problem upgrading rbenv.

The original code is:

```
#Install o rbenv
include_recipe "rbenv::default"
include_recipe "rbenv::ruby_build"

rbenv_ruby "1.9.3-p286" do
  ruby_version "1.9.3-p286"
  global true
end

rbenv_gem "bundler" do
  ruby_version "1.9.3-p286"
end
```

Then I changed just the ruby version to p362:

```
#Install o rbenv
include_recipe "rbenv::default"
include_recipe "rbenv::ruby_build"

rbenv_ruby "1.9.3-p362" do
  ruby_version "1.9.3-p362"
  global true
end

rbenv_gem "bundler" do
  ruby_version "1.9.3-p362"
end
```

And I got this erro message:
**STDERR: rbenv: no such command `install'**

If I try to run "sudo /opt/rbenv/bin/rbenv install 1.9.3-p362", I got the same message, but without the "sudo" command, every thing goes right.

The error output:

```
[2013-01-14T20:57:27+00:00] INFO: rbenv_ruby[1.9.3-p362] is building, this may take a while...

================================================================================
Error executing action `install` on resource 'rbenv_ruby[1.9.3-p362]'
================================================================================

Chef::Exceptions::ShellCommandFailed
------------------------------------

---- Begin output of /opt/rbenv/bin/rbenv install 1.9.3-p362 ----
STDOUT:
STDERR: rbenv: no such command `install'
---- End output of /opt/rbenv/bin/rbenv install 1.9.3-p362 ---
Ran /opt/rbenv/bin/rbenv install 1.9.3-p362 returned 1

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/rbenv/providers/ruby.rb:35:in `block in class_from_file'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/clicksign-test-rbenv/recipes/default.rb

 16: rbenv_ruby "1.9.3-p362" do
 17:   ruby_version "1.9.3-p362"
 18:   global true
 19: end
 20:

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/clicksign-test-rbenv/recipes/default.rb:16:in `from_file'

rbenv_ruby("1.9.3-p362") do
  action :install
  retries 0
  retry_delay 2
  cookbook_name "clicksign-test-rbenv"
  recipe_name "default"
  ruby_version "1.9.3-p362"
  global true
end
```

Can you help me?

Thanks,
Michael

**Comment by mbbernstein** [comment]
I manually run this and worked:

```
sudo su -l rbenv
export RBENV_ROOT=/opt/rbenv
export PATH=/opt/rbenv/shims:/opt/rbenv/bin:/opt/rbenv/bin/rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
rbenv install 1.9.3-p362
/opt/rbenv/versions/1.9.3-p362/bin/gem install bundler -q --no-rdoc --no-ri -v "1.2.3"
```

@deepak @reset: Can you check this?

Thanks,

Michael

**Comment by srenatus** [comment]
BTW I hit the same using Ubuntu 12.10 (cloud image); everything works fine using CentOS 6.4.

**Comment by mbbernstein** [comment]
Since I'm using AWS, if I need to change the ruby version I change the instance.

**Comment by chulkilee** [comment]
This is fixed by #41

BTW note that Ubuntu sudo by default reset PATH so that `rbenv-install` is not in the path within sudo environment.

Updating `/etc/sudoers` as follows did work for me before using the updated cookbook (1.5.0)

```
Defaults    secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rbenv/bin"
```

**Comment by chulkilee** [comment]
Found that t ohai gets languages.ruby variable at the beginning of the client run so that updating global (default) ruby version during chef-client will not be effective following recipes. It seems like ohai should be reloaded after installing new ruby.

I haven't tested that approach - I just ran chef-client again to pick up new ruby :)
