### ISSUE TITLE
Ruby gem are installed for root user & group instead of rbenv

### ISSUE THREAD

**Issue by guidomb** [RiotGamesCookbooks/rbenv-cookbook#27]
I'm setting a virtual environment for developing Ruby On Rails applications using vagrant. The problem is that after the VM is successfully provisioned (after installing rbenv and gem bundler) when I hit `bundler install` it crashes trying to install `therubyracer`. This is the error I get

```
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /opt/rbenv/versions/1.9.3-p327/bin/ruby extconf.rb 
checking for main() in -lpthread... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/opt/rbenv/versions/1.9.3-p327/bin/ruby
    --with-pthreadlib
    --without-pthreadlib
    --enable-debug
    --disable-debug
/opt/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in `initialize': Permission denied - /opt/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/.location.yml (Errno::EACCES)
    from /opt/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in `open'
    from /opt/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/libv8-3.11.8.13-x86_64-linux/ext/libv8/location.rb:15:in `load!'
    from /opt/rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/libv8-3.11.8.13-x86_64-linux/lib/libv8.rb:6:in `configure_makefile'
    from extconf.rb:32:in `<main>'


Gem files will remain installed in /home/vagrant/.bundler/tmp/20201/gems/therubyracer-0.11.4 for inspection.
Results logged to /home/vagrant/.bundler/tmp/20201/gems/therubyracer-0.11.4/ext/v8/gem_make.out

An error occurred while installing therubyracer (0.11.4), and Bundler cannot continue.
Make sure that `gem install therubyracer -v '0.11.4'` succeeds before bundling.
```

After doing some research I found that all the gems installed by bundler are installed for user and group user instead of rbenv. So `therubyracer` gem cannot read the header files. I guess this is a bug or I am doing something wrong.

Here I leave you the snippert of code I use to install rbenv

``` ruby
include_recipe "rbenv::default"
include_recipe "rbenv::ruby_build"

rbenv_ruby '1.9.3-p327' do
  global true
end

rbenv_gem "bundler" do
  ruby_version '1.9.3-p327'
end
```

and my `Vagrantfile` looks like this

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'berkshelf/vagrant'

Vagrant::Config.run do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.forward_port 3000, 3000

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
    chef.add_recipe "rails_env"
    chef.json = {
      rbenv: {
        group_users: ['vagrant']
      }
    }
  end

end
```

I also pushed a all the code needed to reproduce this issue in a public repository so you can check it out. https://github.com/guidomb/env_test

The make it run you need vagrant & berkshelf. You can download Vagrant from [here](http://downloads.vagrantup.com/). After installing Vagrant you need to install berkshelf by doing `vagrant gem install berkshelf`. Then to reproduce the issue

``` bash
git clone https://github.com/guidomb/env_test
cd env_test
vagrant up
vagrant ssh
cd /vagrant
bundle install
```

**Comment by guidomb** [comment]
I could finally resolve my problem by replacing this cookbook with https://github.com/fnichol/chef-rbenv and installing rbenv and the rubies for the vagrant user. Something that I could not figure out how to do with this cookbook

**Comment by stevenharman** [comment]
Other than switching to a different cookbook, is there a way to get this fixed?

**Comment by guidomb** [comment]
I guess that the fix would be to be able to install rbenv and ruby for a user provided by consumer of the cookbook. This is how I configured rbenv in my environment. You can check it in http://github.com/Wolox/rails_env

**Comment by stevenharman** [comment]
Which of course this cookbook does now allow you to do, correct?

**Comment by guidomb** [comment]
Yes, https://github.com/fnichol/chef-rbenv allowed me to install rbenv for vagrant user.

**Comment by stevenharman** [comment]
So you switched cookbooks entirely, yes? You're using `ruby_build` to build the rubies and `chef-rbenv` to install them... hence you switched away from this cookbook. :)

**Comment by guidomb** [comment]
Correct

**Comment by ivey** [comment]
You've always been able to configure the user and group. 1902b152c64d6a3d3f42bafc65b876adf3062cca made it so you can do so via attributes.

My guess is you want to drop the `global true` and specify your own user/group.
