### ISSUE TITLE
Adding rbenv with librarian-chef gives: "topological sort failed"

### ISSUE THREAD

**Issue by emiellohr** [RiotGamesCookbooks/rbenv-cookbook#82]
Adding rbenv with librarian-chef fails with the following error message:

```
/Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:152:in `block in tsort_each': topological sort failed: ["windows", "powershell"] (TSort::Cyclic)
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:210:in `block (2 levels) in each_strongly_connected_component_from'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `each'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:209:in `block in each_strongly_connected_component_from'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `each'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:11:in `tsort_each_child'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:203:in `each_strongly_connected_component_from'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each_key'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
    from /Users/elohr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/tsort.rb:135:in `tsort'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/manifest_set.rb:31:in `sort'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/resolver.rb:73:in `sort'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/resolver.rb:19:in `resolve'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/action/resolve.rb:26:in `run'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/cli.rb:169:in `resolve!'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/cli.rb:113:in `update'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/cli.rb:31:in `returning_status'
    from /Users/elohr/.rvm/gems/ruby-2.0.0-p247@avayo-chef/gems/librarian-0.1.1/lib/librarian/cli.rb:26:in `block in bin!'
```

Does anyone know a solution or workaround?

**Comment by reset** [comment]
@emiellohr this is a Librarian error and should be filed with them. The dependency list for the rbenv cookbook is pretty small and the constraints are loose. From what I can see there isn't a cyclical dependency described in the metadata and have not had this issue resolving rbenv as a dependency in Berkshelf's resolver.

Please re-open this ticket if you do discover something that I can address to help the problem!

**Comment by emiellohr** [comment]
@reset Thanks for the answer. The cyclic dependency is created by the windows cookbook with depends on powershell that depends on ...... windows...

**Comment by reset** [comment]
boo.
