### ISSUE TITLE
can't run bin/unicorn in vagrant when ebenv installed in /opt ?

### ISSUE THREAD

**Issue by dfang** [RiotGamesCookbooks/rbenv-cookbook#98]
i installed rbenv and ruby in a vagrant box(ubuntu 13.04), rbenv installed to /opt, i can't start unicorn in a rails 4 project with command: bin/unicorn, i also triefd sudo bin/unicorn, or bin/puma... however it works on mac. i don't know if it's a issue related to rbenv. i also tried rbenv-sudo plugin, it fails.

or maybe i need to install rbenv to a user's home diretory instead of /opt ?

here is the log:
`
/vagrant/vendor/bundle/ruby/2.0.0/gems/kgio-2.9.2/lib/kgio.rb:21:in`require': cannot load such file -- kgio_ext (LoadError)
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/kgio-2.9.2/lib/kgio.rb:21:in `<top (required)>'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn.rb:6:in`require'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn.rb:6:in `<top (required)>'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/launcher.rb:9:in`require'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/lib/unicorn/launcher.rb:9:in `<top (required)>'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/bin/unicorn:3:in`require'
    from /vagrant/vendor/bundle/ruby/2.0.0/gems/unicorn-4.8.2/bin/unicorn:3:in `<top (required)>'
    from bin/unicorn:16:in`load'
    from bin/unicorn:16:in `<main>'
`

anyone can help ?
thanks

**Comment by dfang** [comment]
tried to vagrant user to rbenv groups, doest not work
